---
apiVersion: v1
kind: Namespace
metadata:
  name: api-gateway
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway-deployment
  namespace: api-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
        version: "1.0.0-SNAPSHOT"
    spec:
      containers:
      - name: api-gateway
        image: exxbrain/api-gateway
        ports:
          - name: web
            containerPort: 80
        readinessProbe:
          httpGet:
            port: web
            path: /actuator/health/readiness
          initialDelaySeconds: 5
          periodSeconds: 5
        livenessProbe:
          httpGet:
            port: web
            path: /actuator/health/liveness
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 2
---
apiVersion: v1
kind: Service
metadata:
  name: api-gateway
  namespace: api-gateway
spec:
  type: ClusterIP
  selector:
    app: api-gateway
  ports:
  - name: web
    port: 80
    targetPort: 80

