apiVersion: skaffold/v2beta9
kind: Config
metadata:
  name: gateway
build:
  artifacts:
    - image: exxbrain/otus-gateway
      jib: {}
deploy:
  helm:
    releases:
      - name: gateway
        chartPath: ../helm-charts/charts/gateway
        setValues:
          authUrl: http://keycloak-http/otusapp/dzakharov/auth
          discoveryService: discovery-service
          issuerUrl: http://arch.homework/otusapp/dzakharov
        artifactOverrides:
          image:
            name: exxbrain/otus-gateway
