apiVersion: skaffold/v2beta9
kind: Config
metadata:
  name: gateway
build:
  artifacts:
    - image: exxbrain/otus-gateway
      jib: {}
deploy:
  helm:
    releases:
      - name: gateway
        namespace: app
        createNamespace: true
        chartPath: ../helm-charts/charts/gateway
        artifactOverrides:
          image:
            name: exxbrain/otus-gateway
