apiVersion: skaffold/v2beta6
kind: Config
build:
  tagPolicy:
    sha256: { }
  artifacts:
    - image: exxbrain/arch-keycloak
  local: { }
deploy:
  helm:
    releases:
      - name: keycloak
        namespace: identity
        chartPath: dev-charts
        valuesFiles:
          - dev-values.yaml
        artifactOverrides:
          image: exxbrain/arch-keycloak