server:
  port: 80

logging:
  level:
    root: DEBUG
    org.springframework.web: INFO
    org.springframework.security: TRACE
    org.springframework.security.oauth2: TRACE
    org.springframework.cloud.gateway: TRACE

management:
  endpoint:
    metrics:
      enabled: true
    prometheus:
      enabled: true
    health:
      show-details: always
    gateway:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"

spring:
  application:
    name: gateway

  security:
    oauth2:
      client:
        registration:
          gateway:
            provider: keycloak
            client-id: gateway
            client-secret: secret
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope: openid,profile,email
        provider:
          keycloak:
            authorization-uri: "${AUTH_URL}/realms/arch/protocol/openid-connect/auth"
            token-uri: "${AUTH_URL}/realms/arch/protocol/openid-connect/token"
            user-info-uri: "${AUTH_URL}/realms/arch/protocol/openid-connect/userinfo"
            user-name-attribute: "preferred_username"
            jwk-set-uri: "${AUTH_URL}/realms/arch/protocol/openid-connect/certs"
      resourceserver:
        jwt:
          issuer-uri: "${AUTH_URL}/realms/arch"

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      default-filters:
        - TokenRelay
        - RemoveRequestHeader=Cookie
        - AddResponseHeader=X-Response-Default-Foo, Default-Bar

      routes:
        # =====================================
        - id: orders
          uri: "lb://order-service"
          predicates:
          - Path=/orders/**
  jmx:
    enabled: false
