apiVersion: skaffold/v2beta9
kind: Config
metadata:
  name: order-service
build:
  artifacts:
  - image: order-service
    jib: {}
deploy:
  helm:
    releases:
      - name: order-service
        namespace: app
        createNamespace: true
        chartPath: ../helm-charts/charts/order-service
        artifactOverrides:
          image:
            name: order-service
