apiVersion: skaffold/v2beta9
kind: Config
metadata:
  name: order-service
build:
  artifacts:
  - image: order-service
    jib: {}
deploy:
  helm:
    releases:
      - name: order-service
        chartPath: ../helm-charts/charts/order-service
        setValues:
          authUrl: http://keycloak-http/otusapp/dzakharov/auth
          issuerUrl: http://arch.homework/otusapp/dzakharov
          dbUrl: jdbc:postgresql://postgres:5432/order_service?user=postgres&password=12345
          postgresql:
            enabled: false
        artifactOverrides:
          image:
            name: order-service
