server:
  port: ${PORT:8761}

spring:
  application:
    name: discovery-service

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    service-url:
      defaultZone: ${DEFAULT_ZONE:http://localhost:8761/eureka/}
  server:
    waitTimeInMsWhenSyncEmpty: 0

management:
  endpoint:
    metrics:
      enabled: true
    prometheus:
      enabled: true
    health:
      show-details: always
      probes:
        enabled: true
  endpoints:
    web:
      exposure:
        include: "*"