openapi: 3.0.0
servers:
  # Added by API Auto Mocking Plugin
  - description: SwaggerHub API Auto Mocking
    url: https://virtserver.swaggerhub.com/exxbrain2/billing_service/1.0.0
info:
  description: This is the Billing Service API
  version: "1.0.0"
  title: Order Service API
  contact:
    email: exxbrain@gmail.com
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
tags:
  - name: users
    description: Operations available to regular users
paths:
  /billing/{orderId}/purchase:
    get:
      tags:
        - users
      summary: make a purchase
      operationId: purchaseOrder
      description: Make an order purchase
      parameters:
        - name: orderId
          in: path
          description: ID of order
          required: true
          schema:
            type: string
            format: uuid
            example: d290f1ee-6c54-4b01-90e6-d701748f0851
      responses:
        '204':
          description: order purchased
        '400':
          description: 'invalid input, object invalid, no money'