name: ci-order-service

on:
  push:
    branches:
      - 'main'
    paths:
      - 'order-service/**'
      - '.github/workflows/ci-order-service.yaml'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: exxbrain
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: order-service/.
          push: true
          tags: exxbrain/order-service:0.1.${{ github.run_number }}
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}