name: ci-uaa

on:
  push:
    branches:
      - 'main'
    paths:
      - 'uaa-server/**'
      - '.github/workflows/ci-uaa.yaml'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Build
        uses: docker/build-push-action@v2
        with:
          context: uaa-server/.
          load: true
          push: true
          tags: exxbrain/uaa:latest
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}